import React from "react";
import useBookmarks from "../../hooks/useBookmarks";
import Body from "../components/Body";
import GridRow from "../components/GridRow";
import Saved from "../components/Saved";
import { v4 } from "uuid";
import Head from "next/head";

const BookmarksPage = () => {
  const { userBookmarks } = useBookmarks();
  return (
    <Body>
      <Head>
        <title>Bookmarked API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        <div></div>
        <h1 className="text-3xl font-bold text-white">Bookmarked Movies</h1>
        {userBookmarks?.filter((bookmark) => bookmark.type === "movie")
          .length !== 0 ? (
          <GridRow>
            {userBookmarks
              ?.filter((bookmark) => bookmark.type === "movie")
              .map((movie) => (
                <Saved movie={movie} key={v4()} />
              ))}
          </GridRow>
        ) : (
          <p className="mt-4">No bookmark added</p>
        )}
        <h1 className="text-3xl font-bold text-white">Bookmarked TV Shows</h1>
        {userBookmarks?.filter((bookmark) => bookmark.type === "tv").length !==
        0 ? (
          <GridRow>
            {userBookmarks
              ?.filter((bookmark) => bookmark.type === "tv")
              .map((movie) => (
                <Saved movie={movie} key={v4()} />
              ))}
          </GridRow>
        ) : (
          <p className="mt-4">No bookmark added</p>
        )}
      </div>
    </Body>
  );
};

export default BookmarksPage;
