import React from "react";
import Body from "../components/Body";
import useFavourites from "../../hooks/useFavourites";
import Saved from "../components/Saved";
import GridRow from "../components/GridRow";
import { v4 } from "uuid";
import Head from "next/head";

const FavouritePage = () => {
  const { userFavourites } = useFavourites();
  return (
    <Body>
      <Head>
        <title>Favourite API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        <div></div>
        <h1 className="text-3xl font-bold text-white">Favourite Movies</h1>
        {userFavourites?.filter((favourite) => favourite.type === "movie")
          .length !== 0 ? (
          <GridRow>
            {userFavourites
              ?.filter((favourite) => favourite.type === "movie")
              .map((movie) => (
                <Saved movie={movie} key={v4()} />
              ))}
          </GridRow>
        ) : (
          <p className="mt-4">No favourite added</p>
        )}
        <h1 className="text-3xl font-bold text-white">Favourite TV Shows</h1>
        {userFavourites?.filter((favourite) => favourite.type === "tv")
          .length !== 0 ? (
          <GridRow>
            {userFavourites
              ?.filter((favourite) => favourite.type === "tv")
              .map((movie) => (
                <Saved movie={movie} key={v4()} />
              ))}
          </GridRow>
        ) : (
          <p className="mt-4">No favourite added</p>
        )}
      </div>
    </Body>
  );
};

export default FavouritePage;
