import Head from "next/head";
import { Movie } from "../../interface";
import {
  getNowPlaying,
  getPopular,
  getTopRated,
  getTrendingMovies,
} from "./api/movie";
import Dashboard from "../components/Dashboard";

interface IMovie {
  trendingMovies: Movie[];
  nowPlayingMovies: Movie[];
  topRatedMovies: Movie[];
  popularMovies: Movie[];
}

const Home = ({
  trendingMovies,
  nowPlayingMovies,
  topRatedMovies,
  popularMovies,
}: IMovie) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard
        topRatedMovies={topRatedMovies}
        trendingMovies={trendingMovies}
        nowPlayingMovies={nowPlayingMovies}
        popularMovies={popularMovies}
      />
    </>
  );
};

export const getServerSideProps = async () => {
  const [trendingMovies, nowPlayingMovies, topRatedMovies, popularMovies] = [
    await getTrendingMovies(),
    await getNowPlaying(),
    await getTopRated(),
    await getPopular(),
  ];

  return {
    props: {
      trendingMovies: trendingMovies || null,
      nowPlayingMovies: nowPlayingMovies || null,
      topRatedMovies: topRatedMovies || null,
      popularMovies: popularMovies || null,
    },
  };
};

export default Home;
