import React from "react";
import Body from "../components/Body";
import Head from "next/head";

const RecentPage = () => {
  return (
    <Body>
      <Head>
        <title>Recent API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        <div></div>
        <h1 className="text-3xl font-bold text-white">Recent Movies</h1>

        <p className="mt-4">No favourite added</p>

        <h1 className="text-3xl font-bold text-white">Recent TV Shows</h1>

        <p className="mt-4">No favourite added</p>
      </div>
    </Body>
  );
};

export default RecentPage;
